version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
