name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Étape 2 : Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Étape 3 : Installer les dépendances système pour Cypress
      - name: Install Dependencies for Cypress
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk2.0-0 \
            libgtk-3-0 \
            libgbm-dev \
            libnotify-dev \
            libnss3 \
            libxss1 \
            libasound2 libasound2-data || echo "Skipping libasound2"

      # Étape 4 : Installer les dépendances du projet
      - name: Install Dependencies
        run: npm install

      # Étape 5 : Construire l'application Angular
      - name: Build Angular App
        run: npm run build -- --configuration=production

      # Étape 6 : Installer et démarrer un serveur X virtuel pour Cypress
      - name: Setup Virtual Display
        run: |
          sudo apt-get install -y xvfb
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x16 > /dev/null 2>&1 &

      # Étape 7 : Lancer les tests E2E
      - name: Run E2E Tests
        run: npm run e2e
