name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Vérifiez le code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configuration de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Installation des dépendances
      - name: Install Dependencies
        run: npm install

      # Lancer le build Angular
      - name: Build Angular App
        run: npm run build -- --prod

      # Exécution des tests unitaires
      - name: Run Unit Tests
        run: npm run test -- --watch=false --no-progress

      # Exécution des tests E2E
      - name: Run E2E Tests
        run: npm run e2e
